/* This file has to be run after 01-create-db.sql */

\c langreader;

INSERT INTO roles (id, role_name) VALUES (0, 'ROLE_USER'), (1, 'ROLE_ADMIN');

INSERT INTO langs (code, full_name) VALUES
    ('AF', 'Afrikaans'),
    ('SQ', 'Albanian'),
    ('AR', 'Arabic'),
    ('HY', 'Armenian'),
    ('AZ', 'Azerbaijani'),
    ('BE', 'Belarusian'),
    ('BN', 'Bengali'),
    ('BG', 'Bulgarian'),
    ('CA', 'Catalan'),
    ('HR', 'Croatian'),
    ('CS', 'Czech'),
    ('DA', 'Danish'),
    ('NL', 'Dutch'),
    ('EN', 'English'),
    ('EO', 'Esperanto'),
    ('ET', 'Estonian'),
    ('FI', 'Finnish'),
    ('FR', 'French'),
    ('DE', 'German'),
    ('EL', 'Greek'),
    ('HE', 'Hebrew'),
    ('HI', 'Hindi'),
    ('HU', 'Hungarian'),
    ('ZH', 'Chinese'),
    ('IS', 'Icelandic'),
    ('ID', 'Indonesian'),
    ('GA', 'Irish'),
    ('IT', 'Italian'),
    ('JA', 'Japanese'),
    ('KK', 'Kazakh'),
    ('KO', 'Korean'),
    ('LA', 'Latin'),
    ('LV', 'Latvian'),
    ('LT', 'Lithuanian'),
    ('MK', 'Macedonian'),
    ('MS', 'Malay'),
    ('MN', 'Mongolian'),
    ('NE', 'Nepali'),
    ('NO', 'Norwegian'),
    ('FA', 'Persian'),
    ('PL', 'Polish'),
    ('PT', 'Portuguese'),
    ('RO', 'Romanian'),
    ('RU', 'Russian'),
    ('SA', 'Sanskrit'),
    ('SR', 'Serbian'),
    ('SK', 'Slovak'),
    ('SL', 'Slovenian'),
    ('ES', 'Spanish'),
    ('SW', 'Swahili'),
    ('SV', 'Swedish'),
    ('TA', 'Tamil'),
    ('TH', 'Thai'),
    ('TR', 'Turkish'),
    ('UK', 'Ukrainian'),
    ('VI', 'Vietnamese');

INSERT INTO word_types (id, word_type) VALUES (0, 'KNOWN'), (1, 'STUDIED'),(2, 'IGNORED');